# Generated by Django 6.0.6 on 2026-06-08 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='birth_day',
            new_name='birth_date',
        ),
    ]
