# Generated by Django 6.0.6 on 2026-06-16 12:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_alter_review_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.PositiveSmallIntegerField(error_messages={'min_value': 'Оценка должна быть не меньше 0'}, validators=[django.core.validators.MinValueValidator(1, message='Оценка должна быть не меньше 1'), django.core.validators.MaxValueValidator(5, message='Оценка должна быть не больше 5')]),
        ),
    ]
